# -*- coding: utf-8 -*-
"""YumChina_data_exploration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FboTrqQHATC3LL3Z66ObUR_EYraxUCvU
"""

#Gotta lay all of my ducks in a row. Prepare for battle. Battle Ducks. Better
#than any mercenary on the market I'm sure.

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import t, ttest_1samp, ttest_ind

#A feast for the eyes at the expense of brain power and the illusion of comprehension

pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',100)

url = 'https://raw.githubusercontent.com/augurnaut/YumChina_financial_trading_daily_historical_price_practice/main/YUMC_five_year_daily_historical_stock_prices.csv'
raw = pd.read_csv(url)

raw

raw.dtypes

raw.isnull().sum()

raw.shape

raw.tail(30)

raw_nozeroes = raw[raw['Volume'] != 0]

raw_nozeroes
raw_nozeroes.shape

sns.pairplot(raw_nozeroes, hue = 'tbd')